name: Merge Changelog
description: Compiles the change files into CHANGELOG.md
author: Enterwell
branding:
  color: yellow
  icon: git-merge

inputs:
  changelog-location:
    description: Location of the directory that contains Changelog.md
    required: false
    default: './'
  changes-in-different-location:
    description: Mark this as true if the 'changes' directory exists somewhere else than on the changelog location
    required: false
    default: 'false'
  changes-location:
    description: Location of the 'changes' directory
    required: false
  should-bump-version:
    description: Should the new version be bumped in the appropriate project file
    required: false
    default: 'false'
  path-to-project-file:
    description: 'Path to the project file. If not set, the application will try to automatically determine the project file. Currently supported project types: NPM (package.json) and .NET SDK (*.csproj with the version tag).'
    required: false
  revision-number:
    description: If the revision number is provided, 4 number long versions will be supported. This is write-only, which means the revision number will not be bumped automatically, but only replaced if provided
    required: false
  should-merge-changelog:
    description: Should the newly generated changelog section be merged to the changelog. If set to false, the merge step is skipped
    required: false
    default: 'true'

outputs:
  bumped-semantic-version:
    description: Newly bumped semantic version based on the changes made
  bumped-major-part:
    description: Major part of the newly bumped version
  bumped-minor-part:
    description: Minor part of the newly bumped version
  bumped-patch-part:
    description: Patch part of the newly bumped version
  new-changes:
    description: Changes from the new changelog section

runs:
  using: node16
  main: dist/index.js